services:
  database:
    image: postgres:16
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_LOGIN}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5120:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    image: megokolos/word_map_game:001
    container_name: word_map_game
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_LOGIN}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      ENVIRONMENT: dev
    ports:
      - "2507:8080"

volumes:
  pg_data: