export const ALL_RULES = {
    MANAGE_DICTIONARY: "MANAGE_DICTIONARY",
    WIPE_DICTIONARY: "WIPE_DICTIONARY",
    MANAGE_RATING: "MANAGE_RATING",
    MANAGE_WORLD: "MANAGE_WORLD",
    MANAGE_ROLE: "MANAGE_ROLE",
    MANAGE_EVENT: "MANAGE_EVENT",
    MANAGE_SHOP: "MANAGE_SHOP",
    MANAGE_OFFER: "MANAGE_OFFER"
};