spring:
  datasource:
    url: ${SPRING_DATASOURCE_DB}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: none
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
  mail:
    host: mail.hosting.reg.ru
    port: 587
    username: ${AUTH_EMAIL_USERNAME}
    password: ${AUTH_EMAIL_PASSWORD}
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
        starttls:
          enable: true
          required: true
jwt:
  secret: ${JWT_SECRET}
  expiration:
    access-token-expiration: 15m
    refresh-token-expiration: 14d
auth:
  confirm-by-email: true
confirm:
  code-expiration-time: 300