spring:
  mail:
    host: mail.hosting.reg.ru
    port: 587
    username: ${AUTH_EMAIL_USERNAME}
    password: ${AUTH_EMAIL_PASSWORD}
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
        starttls:
          enable: true
          required: true

auth:
  confirm-by-email: true