spring:
  datasource:
    url: jdbc:postgresql://database:5432/word_map_game
    username: word_map_game_user
    password: word_map_game_password
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisPG10Dialect
        show_sql: true
        format_sql: true
        jdbc:
          batch_size: 10
          batch_versioned_data: true
    hibernate:
      ddl-auto: none
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
  mail:
    host: mail.hosting.reg.ru
    port: 587
    username: ${AUTH_EMAIL_USERNAME}
    password: ${AUTH_EMAIL_PASSWORD}
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
        starttls:
          enable: true
          required: true
  security:
    oauth2:
      client:
        registration:
          yandex:
            client-id: ${YANDEX_CLIENT_ID}
            client-secret: ${YANDEX_CLIENT_SECRET}
            scope:
              - login:email
              - login:info
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: Yandex
        provider:
          yandex:
            authorization-uri: https://oauth.yandex.ru/authorize
            token-uri: https://oauth.yandex.ru/token
            user-info-uri: https://login.yandex.ru/info
            user-name-attribute: default_email
jwt:
  secret: ${JWT_SECRET}
  expiration:
    access-token-expiration: 15m
    refresh-token-expiration: 14d
auth:
  confirm-by-email: true
confirm:
  code-expiration-time: 300