name: Run tests and verify checkstyle

on:
  pull_request:
    branches: [ '**' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build, test and verify
        run: mvn -B verify -f word-map/pom.xml -Dspring.profiles.active=test